# Generated by Django 4.1.7 on 2023-10-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies_orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="buyed_at",
            new_name="purchased_at",
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
